import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getWorldBySlug, getEntityBySlug, getEntityEvents, getActiveSessionForEntity, getPendingDevelopmentCount, getCanonizedDevelopments } from '@/lib/queries';
import { ENTITY_COLORS, ENTITY_LABELS } from '@/lib/utils';
import { getSession } from '@/lib/auth';
import { DeleteEntityButton } from './DeleteEntityButton';
import { AwayMode } from './AwayMode';

export default async function EntityDetailPage({
  params,
}: {
  params: Promise<{ slug: string; entitySlug: string }>;
}) {
  const { slug, entitySlug } = await params;
  const world = await getWorldBySlug(slug);
  if (!world) notFound();

  const entity = await getEntityBySlug(world.id, entitySlug);
  if (!entity) notFound();

  const session = await getSession();
  const isOwner = session?.sub === world.ownerId;
  const content: string[] = JSON.parse(entity.contentJson || '[]');
  const facts: { label: string; value: string }[] = JSON.parse(entity.factsJson || '[]');
  const tags: string[] = JSON.parse(entity.tagsJson || '[]');

  // Fetch entity's history via EventEntityLink join table
  const entityEventLinks = await getEntityEvents(entity.id);

  // Away mode — only for CHARACTER entities
  const activeSession = entity.type === 'CHARACTER'
    ? await getActiveSessionForEntity(entity.id)
    : null;
  const pendingDevCount = activeSession
    ? await getPendingDevelopmentCount(world.id)
    : 0;

  // Canonized story — only for CHARACTER entities
  const canonStory = entity.type === 'CHARACTER'
    ? await getCanonizedDevelopments(entity.id)
    : [];

  // Group events by era
  const historyEras: {
    id: string | null;
    slug: string | null;
    title: string;
    color: string;
    events: typeof entityEventLinks;
  }[] = [];
  const historyEraMap = new Map<string, typeof historyEras[0]>();

  for (const link of entityEventLinks) {
    const eraKey = link.event.eraRef?.id || link.event.era || 'Unknown Era';
    let group = historyEraMap.get(eraKey);
    if (!group) {
      group = {
        id: link.event.eraRef?.id || null,
        slug: link.event.eraRef?.slug || null,
        title: link.event.eraRef?.title || link.event.era || 'Unknown Era',
        color: link.event.eraRef?.color || '#FF6B2C',
        events: [],
      };
      historyEraMap.set(eraKey, group);
      historyEras.push(group);
    }
    group.events.push(link);
  }

  const allRelations = [
    ...entity.relationsFrom.map((r) => ({
      id: r.id,
      label: r.label,
      entity: r.toEntity,
      direction: 'to' as const,
    })),
    ...entity.relationsTo.map((r) => ({
      id: r.id,
      label: r.label,
      entity: r.fromEntity,
      direction: 'from' as const,
    })),
  ];

  return (
    <>
      {/* Hero */}
      <div className="entity-hero">
        <div className="entity-hero-type">
          <span className="entity-dot" style={{ background: ENTITY_COLORS[entity.type], width: 14, height: 14 }} />
          <span className="entity-badge" style={{
            borderColor: `${ENTITY_COLORS[entity.type]}50`,
            color: ENTITY_COLORS[entity.type],
            background: `${ENTITY_COLORS[entity.type]}10`,
          }}>
            {ENTITY_LABELS[entity.type]}
          </span>
        </div>
        <h1>{entity.title}</h1>
        <p className="entity-hero-summary">{entity.summary}</p>

        {tags.length > 0 && (
          <div className="entity-card-tags" style={{ marginTop: 16 }}>
            {tags.map((tag) => (
              <span key={tag} className="entity-tag">{tag}</span>
            ))}
          </div>
        )}

        {isOwner && (
          <div style={{ display: 'flex', gap: 8, marginTop: 16 }}>
            <Link href={`/worlds/${slug}/entities/${entitySlug}/edit`} className="btn btn-secondary btn-sm">
              Edit
            </Link>
            <DeleteEntityButton slug={slug} entityId={entity.id} entityTitle={entity.title} />
          </div>
        )}
      </div>

      {/* Dossier Layout */}
      <div className="entity-dossier">
        {/* Main Content */}
        <div className="entity-content">
          {content.length > 0 && (
            <>
              <h3>Lore</h3>
              <p className="section-description">The backstory and description of this entity, written by you or generated by AI.</p>
              {content.map((paragraph, i) => (
                <p key={i}>{paragraph}</p>
              ))}
            </>
          )}

          {entityEventLinks.length > 0 && (
            <>
              <h3 style={{ marginTop: 32 }}>History</h3>
              <p className="section-description">Timeline events this entity was involved in, grouped by era.</p>
              <div className="entity-history">
                {historyEras.map((eraGroup) => (
                  <div key={eraGroup.id || eraGroup.title} className="entity-history-era">
                    {eraGroup.slug ? (
                      <Link
                        href={`/worlds/${slug}/eras/${eraGroup.slug}`}
                        className="entity-history-era-label"
                        style={{ color: eraGroup.color, borderColor: `${eraGroup.color}40` }}
                      >
                        <span className="entity-history-era-dot" style={{ background: eraGroup.color, boxShadow: `0 0 10px ${eraGroup.color}40` }} />
                        {eraGroup.title}
                      </Link>
                    ) : (
                      <div className="entity-history-era-label" style={{ color: eraGroup.color }}>
                        <span className="entity-history-era-dot" style={{ background: eraGroup.color }} />
                        {eraGroup.title}
                      </div>
                    )}

                    {eraGroup.events.map((link) => (
                      <div key={link.id} className="entity-history-event">
                        <div className="entity-history-event-card">
                          <div className="entity-history-event-header">
                            <span className="entity-history-event-date">{link.event.dateLabel}</span>
                            {link.role && link.role !== 'involved' && (
                              <span className="entity-history-role-badge">{link.role}</span>
                            )}
                          </div>
                          <h4 className="entity-history-event-title">{link.event.title}</h4>
                          <p className="entity-history-event-summary">{link.event.summary}</p>
                          <div className="entity-history-event-actions">
                            <Link
                              href={`/worlds/${slug}/map?eventId=${link.event.id}`}
                              className="btn btn-ghost btn-sm"
                            >
                              Show on Map
                            </Link>
                            <Link
                              href={`/worlds/${slug}/graph?eventId=${link.event.id}`}
                              className="btn btn-ghost btn-sm"
                            >
                              Show in Connections
                            </Link>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                ))}
              </div>
              <Link
                href={`/worlds/${slug}/timeline?follow=${entity.id}`}
                className="btn btn-ghost btn-sm"
                style={{ marginTop: 12 }}
              >
                View full timeline &rarr;
              </Link>
            </>
          )}

          {/* Character Story — canonized developments */}
          {entity.type === 'CHARACTER' && canonStory.length > 0 && (
            <>
              <h3 style={{ marginTop: 32 }}>Story</h3>
              <p className="section-description">What has happened to this character — approved AI-generated stories in chronological order.</p>
              <div className="character-story">
                {canonStory.map((dev) => (
                  <div key={dev.id} className="character-story-entry">
                    <div className="character-story-meta">
                      <span className="character-story-type-badge" data-type={dev.type.toLowerCase()}>
                        {dev.type.replace('_', ' ').toLowerCase()}
                      </span>
                      {dev.dateLabel && (
                        <span className="character-story-date">{dev.dateLabel}</span>
                      )}
                      {dev.era && (
                        <span className="character-story-era" style={{ color: dev.era.color }}>
                          {dev.era.title}
                        </span>
                      )}
                    </div>
                    <h4 className="character-story-title">{dev.title}</h4>
                    <div className="character-story-content">
                      {dev.content.split('\n').filter(Boolean).map((paragraph, i) => (
                        <p key={i}>{paragraph}</p>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </>
          )}

          {entity.type === 'CHARACTER' && canonStory.length === 0 && isOwner && !activeSession && (
            <div className="empty-state-inline" style={{ marginTop: 32 }}>
              <p className="muted">No story yet. Turn on AI Storytelling below to let this character start living their own life — you&apos;ll review everything before it becomes official.</p>
            </div>
          )}
        </div>

        {/* Sidebar */}
        <div>
          {/* Facts */}
          {facts.length > 0 && (
            <div className="entity-sidebar-section">
              <h4>Facts</h4>
              <div className="fact-list">
                {facts.map((fact) => (
                  <div key={fact.label} className="fact-item">
                    <span className="fact-label">{fact.label}</span>
                    <span className="fact-value">{fact.value}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Relations */}
          {allRelations.length > 0 && (
            <div className="entity-sidebar-section">
              <h4>Connections</h4>
              <div className="relation-list">
                {allRelations.map((rel) => (
                  <Link
                    key={rel.id}
                    href={`/worlds/${slug}/entities/${rel.entity.slug}`}
                    className="relation-card"
                  >
                    <span
                      className="entity-dot"
                      style={{ background: ENTITY_COLORS[rel.entity.type], width: 8, height: 8 }}
                    />
                    <div>
                      <div className="relation-card-name">{rel.entity.title}</div>
                      <div className="relation-card-label">{rel.label}</div>
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          )}

          {/* Away Mode — only for CHARACTER entities */}
          {entity.type === 'CHARACTER' && isOwner && (
            <AwayMode
              slug={slug}
              entityId={entity.id}
              entityTitle={entity.title}
              existingSession={activeSession ? {
                id: activeSession.id,
                status: activeSession.status,
                scope: activeSession.scope,
                personalityPrompt: activeSession.personalityPrompt,
                constraints: activeSession.constraints,
                frequency: activeSession.frequency,
                _count: { developments: 0 },
              } : null}
              pendingCount={pendingDevCount}
            />
          )}
        </div>
      </div>
    </>
  );
}
